/P1/mechanical_press:
  ros__parameters:
    manual:
      force: 5.0
      velocity: 300.0
    approach:
      force: 3.0
      velocity: 200.0
    press:
      force: 10.0
      velocity: 100.0
    return:
      force: 4.0
      velocity: 400.0
    home:
      position: 0.0
    start:
      position: 0.0
    end:
      position: 0.0
